"""add habitCheckIns date column

Revision ID: 02bb5d421faf
Revises: 5024966bfb1d
Create Date: 2023-09-13 15:06:32.032488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bb5d421faf'
down_revision = '5024966bfb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitcheckins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitcheckins', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
