"""add equipped column

Revision ID: 058c025f29fb
Revises: 1354a6a15cf2
Create Date: 2023-09-15 11:03:36.484954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058c025f29fb'
down_revision = '1354a6a15cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventoryItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped', sa.Boolean(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('equipped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('inventoryItems', schema=None) as batch_op:
        batch_op.drop_column('equipped')

    # ### end Alembic commands ###
