"""add equipped column

Revision ID: 1354a6a15cf2
Revises: 7f44cc969a74
Create Date: 2023-09-15 11:02:15.444431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1354a6a15cf2'
down_revision = '7f44cc969a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_weapon', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('equipped_weapon')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('equipped')

    # ### end Alembic commands ###
