"""<descriptive message>


Revision ID: 318f93b3ddf6
Revises: 294d3d6e8075
Create Date: 2023-09-04 09:34:44.219437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318f93b3ddf6'
down_revision = '294d3d6e8075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
