"""add habitCheckIns

Revision ID: 5024966bfb1d
Revises: 0a069394b1e4
Create Date: 2023-09-13 11:03:06.792917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5024966bfb1d'
down_revision = '0a069394b1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitcheckins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habitcheckins_habit_id_habits')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habitcheckins')
    # ### end Alembic commands ###
