"""update models with dates

Revision ID: aa91c20814af
Revises: da22ad2a4bcb
Create Date: 2023-09-12 15:48:54.739967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa91c20814af'
down_revision = 'da22ad2a4bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('frequency')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
