"""add levels and xp

Revision ID: def306a789fa
Revises: 058c025f29fb
Create Date: 2023-09-19 10:16:11.176225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def306a789fa'
down_revision = '058c025f29fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('level')

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('level')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
