"""add monster table

Revision ID: f5b16470bd55
Revises: b11b87888abb
Create Date: 2023-09-14 09:58:37.759222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b16470bd55'
down_revision = 'b11b87888abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('atk_stat', sa.Integer(), nullable=True),
    sa.Column('def_stat', sa.Integer(), nullable=True),
    sa.Column('magic_stat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monsters')
    # ### end Alembic commands ###
